# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac7c9ebcb0e5cd3d4e5d6806712522d3d03d657d1412340aa33d06d50cb975c1073b8ff642d7adc266e43e6da88e5a6c364a349e22c6306a840aeb5c1bbbb87c

test:
  secret_key_base: 5ff2caa4a62c7b13225bf42c8747026bbd8000dcbc210f79976c803c684f6a595f32d654a295f08af6ef91c80e11dc3833e34b9b2b21f743fd7d3b4b8232ec0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
